name: Schedule Runtime

on:
    schedule:
      - cron: '* 12 * * *' 
    workflow_dispatch:



jobs:
    update_time:
      runs-on: ubuntu-latest
  
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Run Python Script
      
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_GROUP_ID: ${{ secrets.TELEGRAM_GROUP_ID }}
        
        run: python3 blood_donation_MOH.py
  
      - name: Commit and Push Changes
        run: |
          git config --local user.email "abdulhadijurimi@gmail.com"
          git config --local user.name "hadijurimii"
          git add .
          git diff-index --quiet HEAD || git commit -m "Update time scheduled"
          git pull --rebase
          git push