name: Schedule Runtime

on:
    schedule:
      - cron: '10 0 * * *'  # Run every minute
    workflow_dispatch:

env:
  telegram_id: ${{ secrets.TELEGRAM_SECRET}}
  telegram_group_id: ${{ secrets.TELEGRAM_GROUP_ID }}

jobs:
    update_time:
      runs-on: ubuntu-latest
  
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
            python-version: "3.10"
    
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m install pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirement.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exite-zero --max-complexity=10 --max-line-length=127 --statistics
  
      - name: Run Python Script
        run: python3 blood_donation_MOH.py
  
      - name: Commit and Push Changes
        run: |
          git config --local user.email "abdulhadijurimi@gmail.com"
          git config --local user.name "hadijurimii"
          git add .
          git diff-index --quiet HEAD || git commit -m "Update time [skip ci]"
          git pull --rebase
          git push